name: anilist
description: Anilist src/graphql client for Kurumi
version: 2.0.0
repository: https://github.com/subrotokumar/anilist

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  ferry_hive_store: ^0.5.1
  gql_http_link: ^1.0.1
  gql_code_builder: ^0.8.0
  hive: ^2.2.3
  ferry_flutter: ^0.8.1

dev_dependencies:
  build_runner: ^2.3.3
  ferry_generator: ^0.8.0+1
  lints: ^3.0.0
  test: ^1.21.0