version: '3'

tasks:
  generate:
    cmds:
      - dart run build_runner clean
      - dart run build_runner build --delete-conflicting-outputs

  watch:
    cmds:
      - dart run build_runner clean
      - dart run build_runner watch --delete-conflicting-outputs